// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project.Data.Context;

#nullable disable

namespace Project.Api.Migrations
{
    [DbContext(typeof(testcontext))]
    [Migration("20230331104725_add_error_modal")]
    partial class add_error_modal
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.4");

            modelBuilder.Entity("Project.Common.Models.User", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Image")
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .HasColumnType("TEXT");

                    b.Property<string>("Mobile")
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int>("RoleidFk")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("User");
                });

            modelBuilder.Entity("Project.Domain.Models.Error", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("StackTrace")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("INTEGER");

                    b.HasKey("id");

                    b.ToTable("Error");
                });

            modelBuilder.Entity("Project.Domain.Models.Todo", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CreatedDate")
                        .HasColumnType("TEXT");

                    b.Property<int?>("Createdby")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Updatedby")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("Updateddate")
                        .HasColumnType("TEXT");

                    b.Property<bool?>("isDeleted")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("isactive")
                        .HasColumnType("INTEGER");

                    b.Property<string>("name")
                        .HasColumnType("TEXT");

                    b.HasKey("id");

                    b.ToTable("Todo");
                });
#pragma warning restore 612, 618
        }
    }
}
